### PR TITLE
Fix corefx build command

### PR DESCRIPTION
**Pull request by danmosemsft**
Relates to https://github.com/dotnet/core-eng/issues/4610

@stephentoub @alexperovich

### CODE REVIEW

**Comment by stephentoub** [comment]
Presumably the wcf build-managed also needs to be fixed?
https://github.com/dotnet/source-indexer/pull/15/files#diff-1f8dbedfdaac27a03fdfcbe7c89c2d64R69

**Comment by danmosemsft** [comment]
No WCF apparently hasn't picked up that work. CoreCLR and MSBuild are broken though:
https://mseng.visualstudio.com/Tools/_build/results?buildId=7733155&view=logs

**Comment by danmosemsft** [comment]
I'm going to merge this without PR 😨 so we can see if it works tonight.

**Comment by danmosemsft** [comment]
https://mseng.visualstudio.com/Tools/_build/results?buildId=7739270&view=logs

**Comment by danmosemsft** [comment]
@alexperovich any idea why https://mseng.visualstudio.com/Tools/_build/results?buildId=7739279&view=logs jammed? Although the next one seems to have worked.

**Comment by alexperovich** [comment]
@danmosemsft the app service deployment isn't always super reliable because we are deploying so many files.

**Pull request merged**
