### PR TITLE
Update source-indexer for dotnet/runtime

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @alexperovich, @ViktorHofer, @danmosemsft

### CODE REVIEW

**Comment by alexperovich** [comment]
Thanks for this. I was working on it but didn't have the command quite right yet.

**Comment by ViktorHofer** [comment]
This will likely break in the future again when we convert the coreclr scripts to msbuild.

**Comment by stephentoub** [comment]
> This will likely break in the future again when we convert the coreclr scripts to msbuild.

Please update this when that changes.

In the meantime, it's already "broken" so working is better than not ;)

**Comment by ViktorHofer** [comment]
Right, thanks for fixing this.

**Comment by stephentoub** [comment]
@alexperovich, we're now failing the build because dotnet/runtime requires long paths to be enabled:
```
  fatal: cannot create directory at 'src/installer/test/Assets/TestProjects/AppWithSubDirs/Sentence/This is a really, really, really, really, really, really, really, really, really, really, really, really, really, really long file name for punctuation': Filename too long
##[warning]EXEC(0,0): Warning : Clone succeeded, but checkout failed.
```
Can you help fix the system appropriately?

**Comment by alexperovich** [comment]
Working on it.

**Pull request merged**
