### PR TITLE
Add maui to source index

### PR DESCRIPTION
**Pull request by joperezr**
cc: @ericstj @rmarinho

### CODE REVIEW

**Comment by ericstj** [comment]
Did you want to schedule a validation build to test this?

**Comment by ericstj** [comment]
Ah, I see you queued https://dev.azure.com/dnceng/internal/_build/results?buildId=2599789&view=results

**Comment by rmarinho** [comment]
We might need to tweak some artifacts folder we see there or is that normal ? 
Screenshot 2024-12-11 at 22 54 13

**Comment by joperezr** [comment]
> We might need to tweak some artifacts folder we see there or is that normal ? 

Do you mean the fact that the artifacts folder is visible to begin with or some of its contents? The fact that is visible is normal I believe, as I see it for other repos as well.

**Comment by joperezr** [comment]
> I also think it s missing our platform code with specific iOS or android target framework. Does the tool support that?

No, the tool only allows to target a single configuration

**Comment by rmarinho** [comment]
Ok I think we can merge this if possible.

**Comment by ericstj** [comment]
LGTM

**Pull request merged**
